# This is a basic workflow to help you get started with Actions

name: Push To Yandex Cloud CR

permissions:
  id-token: write  # Required for get-iam-token

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "build" and "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:0.0.2
        with:
          sa_id: ajep6pdp79imlp76gidn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: iam
          password: ${{ steps.get-iam-token.outputs.access_token }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpk28lsfu91rns28316
          CR_REPOSITORY: yc-coi-github-action
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@b22db2965c8af6bf0980e8b026c5e80ad6e15adf
        env:
          IMAGE_URL: cr.yandex/crpk28lsfu91rns28316/yc-coi-github-action:${{ github.sha }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1gbmkj63hnlfu8877sn
          vm-name: yc-action-demo
          vm-service-account-id: ajepa75j7t2ki57l5i9m
          vm-cores: 2
          vm-memory: 2 GB
          vm-core-fraction: 100
          vm-zone-id: ru-central1-a
          vm-subnet-id: e9bobc1ueq7aue8csi6m
          vm-disk-type: network-hdd
          vm-disk-size: 64GB
          user-data-path: './user-data.yaml'
          docker-compose-path: './docker-compose.yaml'
